version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "pr: dependency-update"
    schedule:
      interval: "daily"

  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/"
    labels:
      - "pr: dependency-update"
    schedule:
      interval: "daily"
