name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DEFAULT_PYTHON: 3.9

jobs:
  code-quality:
    runs-on: "ubuntu-latest"
    name: Check code quality
    steps:
      - uses: "actions/checkout@v2"
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt
      - name: Run pre-commit checks
        run: |
          SKIP=no-commit-to-branch pre-commit run --hook-stage manual --all-files --show-diff-on-failure
      - name: Pylint review
        run: |
          pylint deebotozmo
