# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v3

      - name: 🔢 Get release version
        id: version
        uses: home-assistant/actions/helpers/version@master

      - name: 🖊️ Set version number
        run: |
          sed -i '/version=/c\    version="${{ steps.version.outputs.version }}",' "${{ github.workspace }}/setup.py"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: 📦 Build package
        run: python setup.py sdist bdist_wheel

      - name: 📤 Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
